name: 'Terraform'

on:
  workflow_dispatch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: demo
    defaults:
      run:
        shell: bash

    steps:
    - name: repo Checkout
      uses: actions/checkout@v2

    - name: Initialising the terraform
      run: terraform init

    - name: Planning stage for the terraform
      run: terraform plan

    - name: Applying the changes
      run: terraform apply --auto-approve


  Destroyterraform:
    name: 'Destroying the Terraform'
    runs-on: demo
    defaults:
      run:
        shell: bash
    needs: terraform
    
    steps:
      - name: Destroying the infrastructure
        run: terraform destroy --auto-approve
