name: 'tagging'

on:
  push:
    branches:
      - master
    tags:  
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  testing:
    name: 'testing process'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2

    - name: checking whether the tags are valid or not
      run: |
       sudo apt-get install -y dos2unix
       git tag -l
       chmod 777 shell.sh
       dos2unix shell.sh
       pwd
       ls
       ./shell.sh
       git tag -l

    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        cache: maven
