name: 'Terraform'

on:
  workflow_dispatch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
         
    - name: Initialising the terraform
      run: |
         cd dir1
         terraform init

    - name: Planning stage for the terraform
      run: |
         cd dir1
         terraform plan

    - name: Applying the changes
      run: |
         cd dir1
         terraform apply --auto-approve

  terraform-destroy:
    name: 'Terraform destroy'
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        shell: bash

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
         
    - name: Initialising the terraform
      run: |
         cd dir1
         terraform init

    - name: destroying the changes
      run: |
         cd dir1
         terraform destroy --auto-approve
    environment:
        name: tf_destroy
