name: 'Terraform'

on:
  workflow_dispatch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: demo
    defaults:
      run:
        shell: bash

    steps:
    - name: repo Checkout
      uses: actions/checkout@v2

    - name: Initialising the terraform
      run: terraform init

    - name: Planning stage for the terraform
      run: terraform plan

    - name: Applying the changes
      run: terraform apply --auto-approve

jobs:
  terraform:
    name: 'Destroying the Terraform'
    runs-on: demo
    defaults:
      run:
        shell: bash
		
    steps:
    - name: Destroying the infrastructure
      uses: terraform destroy --auto-approve	
	  
