name: 'Terraform'

on:
  workflow_dispatch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
         terraform_version: 0.12.31
         
    - name: Initialising the terraform
      run: terraform init

    - name: Planning stage for the terraform
      run: terraform plan

    - name: Applying the changes
      run: terraform apply --auto-approve
