name: 'trufflehog'

on:
  workflow_dispatch

jobs:
  facadapi:
    name: 'trufflehog'
    runs-on: ubuntu-latest
    env:
      GIT_URL: https://github.com/Srikanth1916/srikanth.git 
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Setup python
      uses: actions/setup-python@v2

    - name: Installing and configuring the trufflehog
      run: |
        pip install trufflehog* -y
        sleep 5
        truffleHog --regex --entropy=False $GIT_URL
